version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build"
  build:
    commands:
      - echo "Entered the build phase"
      - mvn -version
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*